#!/bin/bash

###########################################################################
##  qubes-vpn-ns
##
## Handles DHCP-source DNS addresses & link notification for Qubes VPN VMs.
## To use, set as 'up' and 'down' script with parameter in your VPN config.
##
## Use 'vpn_dns' environment var as override/alternative.
## In openvpn config, format is: setenv vpn_dns 'X.X.X.X  Y.Y.Y.Y [...]'
##
## Christopher Laprise, 2018-2020  -  https://github.com/tasket

set -e
export PATH="$PATH:/usr/sbin:/sbin:/bin"
nspath=/var/run/qubes/qubes-vpn-ns
rm -f $nspath
hostname=$(hostname)

do_notify() {
    if [ ! -e /etc/fedora-release-NONE ]; then
        echo \'"sleep 2; notify-send \"$hostname: $1\"" --icon=$2\' | xargs su - user -c &
    fi
}

load_qubes_virtual_dns() {
    if [ -r /var/run/qubes/qubes-ns ]; then
        . /var/run/qubes/qubes-ns
        return 0
    fi

    if command -v qubesdb-read >/dev/null 2>&1; then
        NS1="$(qubesdb-read /qubes-netvm-primary-dns 2>/dev/null || true)"
        NS2="$(qubesdb-read /qubes-netvm-secondary-dns 2>/dev/null || true)"
    fi

    if [[ -n "$NS1" || -n "$NS2" ]]; then
        return 0
    fi

    echo "Error: failed to determine Qubes virtual DNS addresses." >&2
    return 1
}

is_ipv4_literal() {
    [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
}

filter_ipv4_dns() {
    local dns
    local filtered=()

    for dns in $vpn_dns; do
        if is_ipv4_literal "$dns"; then
            filtered+=("$dns")
        fi
    done

    if [[ ${#filtered[@]} -eq 0 ]]; then
        echo "Error: no IPv4 VPN DNS servers were provided." >&2
        return 1
    fi

    vpn_dns="${filtered[*]}"
}


case "$1" in
up|test-up)
    rm -f $nspath
    if [[ -z "$vpn_dns" ]] ; then
        # Parses DHCP option variables to set DNS address translation:
        for optionname in ${!foreign_option_*} ; do
            option="${!optionname}"
            unset fops; fops=($option)
            if [ ${fops[1]} == "DNS" ] ; then vpn_dns="${fops[2]} $vpn_dns" ; fi
        done
    fi

;;&
up)
    nft flush chain ip qubes dnat-dns
    if [[ -n "$vpn_dns" ]] ; then
        filter_ipv4_dns
        # Set DNS address translation in firewall:
        echo "$vpn_dns " >$nspath
        echo "Using DNS servers $vpn_dns"
        load_qubes_virtual_dns

        vpn_dns_ip4=()
        for DNS in $vpn_dns; do
            vpn_dns_ip4+=("$DNS")
        done

        qubes_dns_ip4=()
        for NS in $NS1 $NS2; do
            if is_ipv4_literal "$NS"; then
                qubes_dns_ip4+=("$NS")
            fi
        done

        if [[ ${#qubes_dns_ip4[@]} -eq 0 ]]; then
            echo "Error: Qubes did not provide any IPv4 virtual DNS addresses." >&2
            do_notify "LINK BLOCKED, NO QUBES DNS!" "dialog-error"
            exit 1
        fi

        for i in $(seq 0 $((${#qubes_dns_ip4[@]} - 1))); do
            if [[ $i < ${#vpn_dns_ip4[@]} ]] ; then
                nft add rule ip qubes dnat-dns iifgroup 2 ip daddr ${qubes_dns_ip4[$i]} tcp dport 53 dnat to ${vpn_dns_ip4[$i]}
                nft add rule ip qubes dnat-dns iifgroup 2 ip daddr ${qubes_dns_ip4[$i]} udp dport 53 dnat to ${vpn_dns_ip4[$i]}
            else
                nft add rule ip qubes dnat-dns iifgroup 2 ip daddr ${qubes_dns_ip4[$i]} tcp dport 53 dnat to ${vpn_dns_ip4[0]}
                nft add rule ip qubes dnat-dns iifgroup 2 ip daddr ${qubes_dns_ip4[$i]} udp dport 53 dnat to ${vpn_dns_ip4[0]}
            fi
        done
        do_notify "LINK IS UP." "network-idle"
    else
        echo "Error: VPN link came up without VPN DNS; refusing to continue in fail-closed mode." >&2
        do_notify "LINK BLOCKED, NO DNS!" "dialog-error"
        exit 1
    fi

;;
test-up)

##  Use test-up parameter to test your basic VPN link before enabling firewall script.
##  Do NOT use beyond testing period.
    if [[ -z "$vpn_dns" ]]; then echo "NO DNS ADDRESS FOUND."; exit 0; fi
    filter_ipv4_dns
    [ -e /etc/resolv.vpnbak ] || cp -a /etc/resolv.conf /etc/resolv.vpnbak
    rm /etc/resolv.conf
    for DNS in $vpn_dns; do
        echo "nameserver $DNS" >>/etc/resolv.conf
    done
    /usr/lib/qubes/qubes-setup-dnat-to-ns
    do_notify "TEST LINK IS UP." "network-idle"

;;
down)
    nft flush chain ip qubes dnat-dns
    do_notify "LINK IS DOWN !" "dialog-error"

;;
esac
